project:
  type: website

website:
  title: "protocolo.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
    left: 
      - practicas.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

