project:
  type: website

website:
  title: "protocolo.github.io"
  navbar:
    class: "light"
    right:
      - text: "Inicio"
        href: "index.qmd"
      - practicas.qmd
      - evidencias.qmd
      - about.qmd
  page-footer:
    center:
      - text: "Contáctanos"
        href: "mailto:proyectoverificacionesvr@gmail.com"
      - icon: github
        href: https://github.com/protocoloVR/protocoloVR.github.io
format:
  html:
    theme: 
    - cosmo
    css: styles.css

editor: visual

