project:
  type: website

website:
  search: false 
  navbar:
    class: "light"
    title: "VIMO"
    # logo: imgs/logo.png
    right:
      - text: "Inicio"
        href: "index.qmd"
      - text: "Protocolo"
        href: practicas.qmd
      - evidencias.qmd
      - about.qmd
  page-footer:
    center:
      - text: "Contáctanos"
        href: "mailto:proyectoverificacionesvr@gmail.com"
      - icon: github
        href: https://github.com/protocoloVR/protocoloVR.github.io
format:
  html:
    theme: 
    - css/styles.scss
    - cosmo
    
    css: css/styles.css

editor: visual

