---
format:
  html:
    toc: false
    grid:
      body-width: 1000px
      
search: false
execute:
  echo: false
listing:
  - id: practicas
    template: js/practicas.ejs
    contents: practicas.yml
---


# Protocolo VIMO
Prepárate para crear y evaluar propuestas de diseño con Realidad Virtual y nuestro protocolo de verificaciones de diseño VIMO (Verificaciones Inmersivas en el Modelado de Objetos), diseñado para que desarrolles nuevas habilidades a través de una experiencia inmersiva en el proceso de diseño. Dirigido a estudiantes y docentes de Diseño Industrial, y otras disciplinas creativas, el protocolo VIMO te guiará paso por paso en la construcción controlada y verificación de bocetos y prototipos inmersivos con Gravity Sketch. 

Lleva tu creatividad y la pasión de diseñar a otra dimensión.

## Requisitos previos

::: {.callout-important}
## Importante leer
:::

1. Verificar la carga del dispositivo: Asegúrate que el dispositivo de Realidad Virtual esté completamente cargado. Recuerda, la duración máxima de la batería al utilizar Gravity Sketch es de aproximadamente 3 horas.
2. Crea tu cuenta en LandingPad: Crea una cuenta educativa en [LandingPad](landingpad.me) para almacenar archivos de referencia, modelos creados en Gravity Sketch y colaborar con otros usuarios en salas LandingPad Collab.
3. Importa recursos: Importa el protocolo de verificaciones VIMO y los recursos de trabajo necesarios (imágenes y/o modelos de referencia) a tu cuenta de LandingPad antes de comenzar su sesión en Gravity Sketch.
4. Optimiza imágenes y modelos: Manten las imágenes por debajo de 2048x2048 px y los modelos por en formato .obj por debajo de 10.000 polígonos para importar al entorno virtual. 
5. Realiza pausas de descanso: Toma descansos cada 30 minutos a 1 hora durante el uso de la herramienta de RV para reducir la fatiga ocular. Si experimentas malestar constante, asegúrate de descansar adecuadamente y cuidar tu salud.

## Protocolo completo


<a href="imgs/protocolo/protocolo_completo.zip" download="Protocolo_para_verificaciones_inmersivas">
<button >Descarga el Protocolo completo <i class="bi bi-download"></i></button> 
</a>
<!-- class="button-34" -->

